version: '3.0'
services:
  plantngo-db:
    container_name: plantngo-db
    image: postgres:14.5
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  plantngo-backend:
    container_name: plantngo-backend
    image: plantngo-backend:latest
    build: .
    env_file: ./.env
    restart: always
    depends_on:
      - plantngo-db
    volumes:
      - .:/opt/app
    ports:
      - 8080:8080
      
  sonarqube:
    image: sonarqube-arm:latest
    depends_on:
      - plantngo-db
    env_file:
      - ./.env
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
